// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // Ahora se retorna la configuración para web si está habilitada.
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiouzNgvu_hh88lKOhgy33S_NvA2yfNc4',
    appId: '1:892878066374:android:681cbeb8c961902ae67dc7',
    messagingSenderId: '892878066374',
    projectId: 'mapspachuca-ae9e8',
    storageBucket: 'mapspachuca-ae9e8.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiouzNgvu_hh88lKOhgy33S_NvA2yfNc4',
    appId: '1:892878066374:web:ebc8be0dbb91976be67dc7',
    messagingSenderId: '892878066374',
    projectId: 'mapspachuca-ae9e8',
    storageBucket: 'mapspachuca-ae9e8.appspot.com',
    authDomain: 'mapspachuca-ae9e8.firebaseapp.com',
    databaseURL: 'https://mapspachuca-ae9e8.firebaseio.com',
    measurementId: 'G-W5SXBR8TH2',
  );
}
